 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Ahmed Nasr
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration =
                                   {
                                		   {
                                				   {PORTCONF_PA0_PORT_NUM,
                                				    PORTCONF_PA0_PIN_NUM,
													PORTCONF_PA0_INITIAL_MODE,
													PORTCONF_PA0_INITIAL_DIRECTION,
													PORTCONF_PA0_INITIAL_LEVEL,
													PORTCONF_PA0_DIRECTION_CHANGEABLE,
													PORTCONF_PA0_MODE_CHANGEABLE,
													PORTCONF_PA0_ACTIVATE_PULLUP},

                                				   {PORTCONF_PA1_PORT_NUM,
                                				    PORTCONF_PA1_PIN_NUM,
													PORTCONF_PA1_INITIAL_MODE,
													PORTCONF_PA1_INITIAL_DIRECTION,
													PORTCONF_PA1_INITIAL_LEVEL,
													PORTCONF_PA1_DIRECTION_CHANGEABLE,
													PORTCONF_PA1_MODE_CHANGEABLE,
													PORTCONF_PA1_ACTIVATE_PULLUP},

                                				   {PORTCONF_PA2_PORT_NUM,
                                				    PORTCONF_PA2_PIN_NUM,
													PORTCONF_PA2_INITIAL_MODE,
													PORTCONF_PA2_INITIAL_DIRECTION,
													PORTCONF_PA2_INITIAL_LEVEL,
													PORTCONF_PA2_DIRECTION_CHANGEABLE,
													PORTCONF_PA2_MODE_CHANGEABLE,
													PORTCONF_PA2_ACTIVATE_PULLUP},

                                				   {PORTCONF_PA3_PORT_NUM,
                                				    PORTCONF_PA3_PIN_NUM,
													PORTCONF_PA3_INITIAL_MODE,
													PORTCONF_PA3_INITIAL_DIRECTION,
													PORTCONF_PA3_INITIAL_LEVEL,
													PORTCONF_PA3_DIRECTION_CHANGEABLE,
													PORTCONF_PA3_MODE_CHANGEABLE,
													PORTCONF_PA3_ACTIVATE_PULLUP},

												   {PORTCONF_PA4_PORT_NUM,
	                                				PORTCONF_PA4_PIN_NUM,
													PORTCONF_PA4_INITIAL_MODE,
													PORTCONF_PA4_INITIAL_DIRECTION,
													PORTCONF_PA4_INITIAL_LEVEL,
													PORTCONF_PA4_DIRECTION_CHANGEABLE,
													PORTCONF_PA4_MODE_CHANGEABLE,
													PORTCONF_PA4_ACTIVATE_PULLUP},

												   {PORTCONF_PA5_PORT_NUM,
													PORTCONF_PA5_PIN_NUM,
													PORTCONF_PA5_INITIAL_MODE,
													PORTCONF_PA5_INITIAL_DIRECTION,
													PORTCONF_PA5_INITIAL_LEVEL,
													PORTCONF_PA5_DIRECTION_CHANGEABLE,
													PORTCONF_PA5_MODE_CHANGEABLE,
													PORTCONF_PA5_ACTIVATE_PULLUP},

												   {PORTCONF_PA6_PORT_NUM,
													PORTCONF_PA6_PIN_NUM,
													PORTCONF_PA6_INITIAL_MODE,
													PORTCONF_PA6_INITIAL_DIRECTION,
													PORTCONF_PA6_INITIAL_LEVEL,
													PORTCONF_PA6_DIRECTION_CHANGEABLE,
													PORTCONF_PA6_MODE_CHANGEABLE,
													PORTCONF_PA6_ACTIVATE_PULLUP},

												   {PORTCONF_PA7_PORT_NUM,
													PORTCONF_PA7_PIN_NUM,
													PORTCONF_PA7_INITIAL_MODE,
													PORTCONF_PA7_INITIAL_DIRECTION,
													PORTCONF_PA7_INITIAL_LEVEL,
													PORTCONF_PA7_DIRECTION_CHANGEABLE,
													PORTCONF_PA7_MODE_CHANGEABLE,
													PORTCONF_PA7_ACTIVATE_PULLUP},

												   {PORTCONF_PB0_PORT_NUM,
													PORTCONF_PB0_PIN_NUM,
													PORTCONF_PB0_INITIAL_MODE,
													PORTCONF_PB0_INITIAL_DIRECTION,
													PORTCONF_PB0_INITIAL_LEVEL,
													PORTCONF_PB0_DIRECTION_CHANGEABLE,
													PORTCONF_PB0_MODE_CHANGEABLE,
													PORTCONF_PB0_ACTIVATE_PULLUP},

												   {PORTCONF_PB1_PORT_NUM,
													PORTCONF_PB1_PIN_NUM,
													PORTCONF_PB1_INITIAL_MODE,
													PORTCONF_PB1_INITIAL_DIRECTION,
													PORTCONF_PB1_INITIAL_LEVEL,
													PORTCONF_PB1_DIRECTION_CHANGEABLE,
													PORTCONF_PB1_MODE_CHANGEABLE,
													PORTCONF_PB1_ACTIVATE_PULLUP},

												   {PORTCONF_PB2_PORT_NUM,
													PORTCONF_PB2_PIN_NUM,
													PORTCONF_PB2_INITIAL_MODE,
													PORTCONF_PB2_INITIAL_DIRECTION,
													PORTCONF_PB2_INITIAL_LEVEL,
													PORTCONF_PB2_DIRECTION_CHANGEABLE,
													PORTCONF_PB2_MODE_CHANGEABLE,
													PORTCONF_PB2_ACTIVATE_PULLUP},

												   {PORTCONF_PB3_PORT_NUM,
													PORTCONF_PB3_PIN_NUM,
													PORTCONF_PB3_INITIAL_MODE,
													PORTCONF_PB3_INITIAL_DIRECTION,
													PORTCONF_PB3_INITIAL_LEVEL,
													PORTCONF_PB3_DIRECTION_CHANGEABLE,
													PORTCONF_PB3_MODE_CHANGEABLE,
													PORTCONF_PB3_ACTIVATE_PULLUP},

												   {PORTCONF_PB4_PORT_NUM,
													PORTCONF_PB4_PIN_NUM,
													PORTCONF_PB4_INITIAL_MODE,
													PORTCONF_PB4_INITIAL_DIRECTION,
													PORTCONF_PB4_INITIAL_LEVEL,
													PORTCONF_PB4_DIRECTION_CHANGEABLE,
													PORTCONF_PB4_MODE_CHANGEABLE,
													PORTCONF_PB4_ACTIVATE_PULLUP},

												   {PORTCONF_PB5_PORT_NUM,
													PORTCONF_PB5_PIN_NUM,
													PORTCONF_PB5_INITIAL_MODE,
													PORTCONF_PB5_INITIAL_DIRECTION,
													PORTCONF_PB5_INITIAL_LEVEL,
													PORTCONF_PB5_DIRECTION_CHANGEABLE,
													PORTCONF_PB5_MODE_CHANGEABLE,
													PORTCONF_PB5_ACTIVATE_PULLUP},

												   {PORTCONF_PB6_PORT_NUM,
													PORTCONF_PB6_PIN_NUM,
													PORTCONF_PB6_INITIAL_MODE,
													PORTCONF_PB6_INITIAL_DIRECTION,
													PORTCONF_PB6_INITIAL_LEVEL,
													PORTCONF_PB6_DIRECTION_CHANGEABLE,
													PORTCONF_PB6_MODE_CHANGEABLE,
													PORTCONF_PB6_ACTIVATE_PULLUP},

												   {PORTCONF_PB7_PORT_NUM,
													PORTCONF_PB7_PIN_NUM,
													PORTCONF_PB7_INITIAL_MODE,
													PORTCONF_PB7_INITIAL_DIRECTION,
													PORTCONF_PB7_INITIAL_LEVEL,
													PORTCONF_PB7_DIRECTION_CHANGEABLE,
													PORTCONF_PB7_MODE_CHANGEABLE,
													PORTCONF_PB7_ACTIVATE_PULLUP},

												   {PORTCONF_PC0_PORT_NUM,
													PORTCONF_PC0_PIN_NUM,
													PORTCONF_PC0_INITIAL_MODE,
													PORTCONF_PC0_INITIAL_DIRECTION,
													PORTCONF_PC0_INITIAL_LEVEL,
													PORTCONF_PC0_DIRECTION_CHANGEABLE,
													PORTCONF_PC0_MODE_CHANGEABLE,
													PORTCONF_PC0_ACTIVATE_PULLUP},

												   {PORTCONF_PC1_PORT_NUM,
													PORTCONF_PC1_PIN_NUM,
													PORTCONF_PC1_INITIAL_MODE,
													PORTCONF_PC1_INITIAL_DIRECTION,
													PORTCONF_PC1_INITIAL_LEVEL,
													PORTCONF_PC1_DIRECTION_CHANGEABLE,
													PORTCONF_PC1_MODE_CHANGEABLE,
													PORTCONF_PC1_ACTIVATE_PULLUP},

												   {PORTCONF_PC2_PORT_NUM,
													PORTCONF_PC2_PIN_NUM,
													PORTCONF_PC2_INITIAL_MODE,
													PORTCONF_PC2_INITIAL_DIRECTION,
													PORTCONF_PC2_INITIAL_LEVEL,
													PORTCONF_PC2_DIRECTION_CHANGEABLE,
													PORTCONF_PC2_MODE_CHANGEABLE,
													PORTCONF_PC2_ACTIVATE_PULLUP},

												   {PORTCONF_PC3_PORT_NUM,
													PORTCONF_PC3_PIN_NUM,
													PORTCONF_PC3_INITIAL_MODE,
													PORTCONF_PC3_INITIAL_DIRECTION,
													PORTCONF_PC3_INITIAL_LEVEL,
													PORTCONF_PC3_DIRECTION_CHANGEABLE,
													PORTCONF_PC3_MODE_CHANGEABLE,
													PORTCONF_PC3_ACTIVATE_PULLUP},

												   {PORTCONF_PC4_PORT_NUM,
													PORTCONF_PC4_PIN_NUM,
													PORTCONF_PC4_INITIAL_MODE,
													PORTCONF_PC4_INITIAL_DIRECTION,
													PORTCONF_PC4_INITIAL_LEVEL,
													PORTCONF_PC4_DIRECTION_CHANGEABLE,
													PORTCONF_PC4_MODE_CHANGEABLE,
													PORTCONF_PC4_ACTIVATE_PULLUP},

												   {PORTCONF_PC5_PORT_NUM,
													PORTCONF_PC5_PIN_NUM,
													PORTCONF_PC5_INITIAL_MODE,
													PORTCONF_PC5_INITIAL_DIRECTION,
													PORTCONF_PC5_INITIAL_LEVEL,
													PORTCONF_PC5_DIRECTION_CHANGEABLE,
													PORTCONF_PC5_MODE_CHANGEABLE,
													PORTCONF_PC5_ACTIVATE_PULLUP},

												   {PORTCONF_PC6_PORT_NUM,
													PORTCONF_PC6_PIN_NUM,
													PORTCONF_PC6_INITIAL_MODE,
													PORTCONF_PC6_INITIAL_DIRECTION,
													PORTCONF_PC6_INITIAL_LEVEL,
													PORTCONF_PC6_DIRECTION_CHANGEABLE,
													PORTCONF_PC6_MODE_CHANGEABLE,
													PORTCONF_PC6_ACTIVATE_PULLUP},

												   {PORTCONF_PC7_PORT_NUM,
													PORTCONF_PC7_PIN_NUM,
													PORTCONF_PC7_INITIAL_MODE,
													PORTCONF_PC7_INITIAL_DIRECTION,
													PORTCONF_PC7_INITIAL_LEVEL,
													PORTCONF_PC7_DIRECTION_CHANGEABLE,
													PORTCONF_PC7_MODE_CHANGEABLE,
													PORTCONF_PC7_ACTIVATE_PULLUP},

												   {PORTCONF_PD0_PORT_NUM,
													PORTCONF_PD0_PIN_NUM,
													PORTCONF_PD0_INITIAL_MODE,
													PORTCONF_PD0_INITIAL_DIRECTION,
													PORTCONF_PD0_INITIAL_LEVEL,
													PORTCONF_PD0_DIRECTION_CHANGEABLE,
													PORTCONF_PD0_MODE_CHANGEABLE,
													PORTCONF_PD0_ACTIVATE_PULLUP},

												   {PORTCONF_PD1_PORT_NUM,
													PORTCONF_PD1_PIN_NUM,
													PORTCONF_PD1_INITIAL_MODE,
													PORTCONF_PD1_INITIAL_DIRECTION,
													PORTCONF_PD1_INITIAL_LEVEL,
													PORTCONF_PD1_DIRECTION_CHANGEABLE,
													PORTCONF_PD1_MODE_CHANGEABLE,
													PORTCONF_PD1_ACTIVATE_PULLUP},

												   {PORTCONF_PD2_PORT_NUM,
													PORTCONF_PD2_PIN_NUM,
													PORTCONF_PD2_INITIAL_MODE,
													PORTCONF_PD2_INITIAL_DIRECTION,
													PORTCONF_PD2_INITIAL_LEVEL,
													PORTCONF_PD2_DIRECTION_CHANGEABLE,
													PORTCONF_PD2_MODE_CHANGEABLE,
													PORTCONF_PD2_ACTIVATE_PULLUP},

												   {PORTCONF_PD3_PORT_NUM,
													PORTCONF_PD3_PIN_NUM,
													PORTCONF_PD3_INITIAL_MODE,
													PORTCONF_PD3_INITIAL_DIRECTION,
													PORTCONF_PD3_INITIAL_LEVEL,
													PORTCONF_PD3_DIRECTION_CHANGEABLE,
													PORTCONF_PD3_MODE_CHANGEABLE,
													PORTCONF_PD3_ACTIVATE_PULLUP},

												   {PORTCONF_PD4_PORT_NUM,
													PORTCONF_PD4_PIN_NUM,
													PORTCONF_PD4_INITIAL_MODE,
													PORTCONF_PD4_INITIAL_DIRECTION,
													PORTCONF_PD4_INITIAL_LEVEL,
													PORTCONF_PD4_DIRECTION_CHANGEABLE,
													PORTCONF_PD4_MODE_CHANGEABLE,
													PORTCONF_PD4_ACTIVATE_PULLUP},

												   {PORTCONF_PD5_PORT_NUM,
													PORTCONF_PD5_PIN_NUM,
													PORTCONF_PD5_INITIAL_MODE,
													PORTCONF_PD5_INITIAL_DIRECTION,
													PORTCONF_PD5_INITIAL_LEVEL,
													PORTCONF_PD5_DIRECTION_CHANGEABLE,
													PORTCONF_PD5_MODE_CHANGEABLE,
													PORTCONF_PD5_ACTIVATE_PULLUP},

												   {PORTCONF_PD6_PORT_NUM,
													PORTCONF_PD6_PIN_NUM,
													PORTCONF_PD6_INITIAL_MODE,
													PORTCONF_PD6_INITIAL_DIRECTION,
													PORTCONF_PD6_INITIAL_LEVEL,
													PORTCONF_PD6_DIRECTION_CHANGEABLE,
													PORTCONF_PD6_MODE_CHANGEABLE,
													PORTCONF_PD6_ACTIVATE_PULLUP},

												   {PORTCONF_PD7_PORT_NUM,
													PORTCONF_PD7_PIN_NUM,
													PORTCONF_PD7_INITIAL_MODE,
													PORTCONF_PD7_INITIAL_DIRECTION,
													PORTCONF_PD7_INITIAL_LEVEL,
													PORTCONF_PD7_DIRECTION_CHANGEABLE,
													PORTCONF_PD7_MODE_CHANGEABLE,
													PORTCONF_PD7_ACTIVATE_PULLUP}
                                		   }
								   };
